README.md

Added Australian Cyber Security Conference (ACSC) in Canberra during April.

Added conference: ACSC

---

README.md

Updated README.md to contain OzSecCon in the list for Melbourne.

Fix OzSecCon Missing Below Table

---

README.md

Now that this is official I'm re-adding it to the repo.
Asked Lidia for rough numbers and will update repo if she's comfortable giving us a figure.

Adding BSides Melbourne

---

README.md

Added AISA Cyber Conference

---

README.md

Adding BSides Brisbane to summary/detail

Add BSides Brisbane

---

README.md

As per https://twitter.com/CrikeyCon/status/1052391711500976128 changing CrikeyCon from February to April.

Change CrikeyCon month Feb->April

---

README.md

URL : https://bsidesdelhi.in
CTF also : https://ctf.bsidesdelhi.in/

Added Bsides Delhi

---

README.md

As per discussion with twitter.com/josephbleroy adding TechNet Tokyo.

Add Technet Tokyo

---

README.md

Adding Threat Con (Nepal)

---

README.md

Asked to add on Twitter via DM from @nanosec_asia

Added Nanosec Asia

---

README.md

Add Melbourne COSAC Enterprise Security Architecture Conference.
Fix typo on location for Security Influence and Trust Summit

Add Melbourne COSAC Enterprise Security Architecture Conference.

---

README.md

- Added `c0con 12` happening in September
- Fixed some formatting

Adding c0c0n [India]

---

README.md

Updated dates and removed platypuscon.

Updated Conferences

---

README.md

Work with @summer_heidi to properly represent Kids Securiday for each region it's currently active witrhin.

Added Kids Securiday

---

README.md

ACSC is no more
ref: https://www.innovationaus.com/2019/01/ACSC-shutters-2019-conference

remove ACSC

---

README.md

Bsides Canberra is 1-2nd May 2020

update BSides Canberra date

---

README.md

Updated month and numbers for WAHCKon

Updated WAHCKon info

---

README.md

Added ROOTCON, Philippines. "ROOTCON is the premier and largest hacking conference in the Philippines"

+ROOTCON, Philippines

---

README.md

Hasn't been active for 2 years

Removed Ruxcon

---

README.md

Added ComfyCon Summer and fixed a typo

Added ComfyCon Summer

---

CONTRIBUTING.md
CONTRIBUTORS.md

Adding a much overdue CONTRIBUTING and CONTRIBUTORS docos.
Hopefully this helps clear up any potential issues we have with people contributing, and establish a reasonable timeline for response.

Adding Contributing.md

---

README.md

Updated entries for ComfyCon and BHASIA
No URL for BHASIA, but will be soon
Moved some | (pipe) alignments

Comfy and BHASIA

---

README.md

I took dates from organizers in the sectalks slack group and updated them here.

Updated more dates from the sectalks slack

---

README.md

Update Date of KSD Mel

---

README.md

* Removed older conferences
* Added next conference date column
* Removed conferences with duplicate locations if they roam
* Updated dates and links
* Added Last Updated line

Post-COVID Update

---

README.md

See https://www.infosec-city.com/sinrlcon

Fix date for SINCON / Infosec in the city

---

README.md

cybercon canberra, MRE, cyberwest

Updates and corrections

---

README.md

Updated BSides Perth date (2023)

Updated BSides Perth date

---

README.md

I updated all conferences that are happening in 2024, and removed the ones that were not.  I added a few new cons as well (hack.syd) and generally tried to update the list.

updated for 2024 conferences

---

README.md

Added the 2024 locked in dates for Melbourne BSides

Melbourne bsides 2024

---

README.md

I saw Kylie was at a conference not on our list so I added it!

added off by one via kylie's post

---

README.md

I added RooCon, purplecon and Gold Coast BSides to the list

added purplecon, bsides goldie, and roocon

---

README.md

This is the first commit for the 2025 schedule.

first commit for the 2025 schedule

---

README.md

added the AISA March event and another Korean event

Paul more tweaks

---

README.md

Add attendee count, provided by organizer @Emil0xA

Add SINCON attendee count

---

README.md

🤦🏼 sorry, should not commit changes late at night, apologies @codingo !

Actually fix SINCON attendee count

---

README.md

Added Cybersec 2025 in Taiwan as well as updated the BSides LV dates

added Cybersec 2025 in Taiwan and updated dates for BSides LV
